# Generated by Django 3.1.7 on 2021-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=16)),
                ('mobile_No', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField()),
            ],
        ),
    ]
